### PR TITLE
TC_14.002.10 | Verify that the warning message is displayed when no matches are found

### PR DESCRIPTION
**Pull request by adiuzhikov**
[TC_14.002.10](https://github.com/orgs/RedRoverSchool/projects/4/views/1?filterQuery=14.002+&pane=issue&itemId=87890218&issue=RedRoverSchool%7CJenkinsQA_JS_2024_fall%7C186)

### CODE REVIEW

**Review by shabaiev — COMMENTED** [review]
no need to add space between it and 1st cy.get

**Comment by adiuzhikov** [comment]
> no need to add space between it and 1st cy.get

I didn't add space, I've added a line!

**Comment by shabaiev** [comment]
> > no need to add space between it and 1st cy.get
> 
> I didn't add space, I've added a line!

yup, there is no need for that either :)

**Review by Alzhan-B — APPROVED** [review]
👌

**Review by NadiyaP — APPROVED** [review]

**Pull request merged**
