### PR TITLE
TC_14.002.17 | Verify that each page in Jenkins has a search box on its top right

### PR DESCRIPTION
**Pull request by AnDerova**
[TC_14.002.17-А](https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/306)
Header > Search Box | Verify that every page in Jenkins has a search box on its top right

### CODE REVIEW

**Review by ivanlashkevich — APPROVED** [review]
The test passed the checks. But there're some suggestions for the test case improvement:
- According to your test case card on Github board your TC is: 'Verify that every page in Jenkins has a search box on its top right'. But in your PR we see a different name for this TC 'Verify that each page in Jenkins has a search box'.
- The test code checks for the visibility of the search box, but it does not explicitly assert that the search box is located in the "top right" of each Jenkins page. The current test only verifies that the search box is present and visible without specifying its position on the page. So, you can either change the TC name or add the neccessary assertion.
Approved.

**Review by Jmadon — APPROVED** [review]
Your test works, but I don't think it's right that you used beforeEach, before each test. I think it will overload the system, because it will be for each test, which is not justified in this case. I would use one test and within it use a loop with a check. The disadvantage is that the test will not be signed as with your test. 

Maybe someone more experienced can confirm or deny what would be the right thing to do in this situation.

Anyway, Approve.

**Comment by AnDerova** [comment]
> Your test works, but I don't think it's right that you used beforeEach, before each test. I think it will overload the system, because it will be for each test, which is not justified in this case. I would use one test and within it use a loop with a check. The disadvantage is that the test will not be signed as with your test.
> 
> Maybe someone more experienced can confirm or deny what would be the right thing to do in this situation.
> 
> Anyway, Approve.

I prefer more granular tests as it better shows a particular problem in case the test fails. I would not think much about performance with many beforeEach calls as this is not a production code.

**Comment by AnDerova** [comment]
Rebase conflict solved

**Review by adiuzhikov — APPROVED** [review]

**Comment by AnDerova** [comment]
> The test passed the checks. But there're some suggestions for the test case improvement:
> 
> * According to your test case card on Github board your TC is: 'Verify that every page in Jenkins has a search box on its top right'. But in your PR we see a different name for this TC 'Verify that each page in Jenkins has a search box'.
> * The test code checks for the visibility of the search box, but it does not explicitly assert that the search box is located in the "top right" of each Jenkins page. The current test only verifies that the search box is present and visible without specifying its position on the page. So, you can either change the TC name or add the neccessary assertion.
>   Approved.

Thank you for the feedback!
I've updated the PR title to align with the test case name.
I completely agree with your second point. The test case primarily verifies the visibility of the search box rather than its exact position. However, the current implementation is based on the acceptance criteria from the user story. I wanted the test case name to reflect the specific part of the user story, so other team members can clearly understand the focus of this test.

**Pull request merged**
