### PR TITLE
add TC_00.000.05 to 'newItemCreateNewItem.cy.js' file

### PR DESCRIPTION
**Pull request by ivanlashkevich**
Added test case 'Create new item from Dashboard dropdown menu'. The test ran successfully locally.

TC_00 000 05

Link to Github board card: https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/145
Link to US: https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/15

### CODE REVIEW

**Review by yanaoreshkevich — APPROVED** [review]
It's LGTM

**Comment by KateVernikovskaya** [comment]
Everything okay? Great job!

**Review by KateVernikovskaya — COMMENTED** [review]
It's LGTM

**Review by KateVernikovskaya — COMMENTED** [review]
test

**Pull request merged**
