### PR TITLE
TC_14.002.16 | Header > Search Box | Finds a build by its number

### PR DESCRIPTION
**Pull request by TatianaBM**
https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/307

### CODE REVIEW

**Comment by mariamednikova** [comment]
Please, delete comments from your test

**Review by ivanlashkevich — APPROVED** [review]
The test passed all steps and checks. Just some recommendations for future implementation to simplify the reviewing process and reading the code in general:
- using variables instead of selectors (mainly in complex tests);
- replacing ordinary 'double-slash' comments with 'cy.log()' method (highlights the test case steps while checking the flow).
Approved

**Comment by TatianaBM** [comment]
> Please, delete comments from your test

removed

**Comment by TatianaBM** [comment]
> The test passed all steps and checks. Just some recommendations for future implementation to simplify the reviewing process and reading the code in general:
> 
> * using variables instead of selectors (mainly in complex tests);
> * replacing ordinary 'double-slash' comments with 'cy.log()' method (highlights the test case steps while checking the flow).
>   Approved

well noted! Comments removed, cy.log() added

**Pull request merged**
