### PR TITLE
TC_00.000-07-A | New Item > Create New item | Verify new item can only be created using unique item names

### PR DESCRIPTION
**Pull request by ivanlashkevich**
Added test case 'Verify new item can only be created using unique item names'. The test passed all checks locally.

TC_00 000 07 Verify new item can only be created using unique item names

Link to Github board card: https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/169
Link to US: https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/15

### CODE REVIEW

**Review by adiuzhikov — APPROVED** [review]
I think it might be a good idea to get Alina or Nalya’s thoughts on whether we should create end-to-end tests. But for now it looks good!

**Comment by NShakiro** [comment]
> I think it might be a good idea to get Alina or Nalya’s thoughts on whether we should create end-to-end tests. But for now it looks good!

Yep, agree. Test looks good, but it brakes  project rule: one test - one assert. I leaved a comment in your TC card, please review

**Review by Negrescu29 — APPROVED** [review]

**Review by KateVernikovskaya — APPROVED** [review]
LGTM!

**Comment by ivanlashkevich** [comment]
Closing pull request cause some conflicts appeared.

**Pull request merged**
