### PR TITLE
TC_04.001.08 | Folder > Rename Folder | Enter a valid folder name with numbers and allowed special characters

### PR DESCRIPTION
**Pull request by wwwser11**
Added a new test case: TC_04.001.08 | Folder > Rename Folder | Enter a valid folder name with numbers and allowed special characters. This test ensures that folder names containing numbers and special characters (e.g., Folder123!@#$) are handled correctly by the renaming functionality.

Changes Made:
Removed renameFolder.cy.js file.
Created a new test file: folderRenameFolder.cy.js.
Added a new test case:
TC_04.001.08 | Folder > Rename Folder | Enter a valid folder name with numbers and allowed special characters.
Implemented a new test to verify renaming a folder with a combination of numbers and allowed special characters.
Added validation to check that the new folder name is displayed correctly in the input field and page title.

### CODE REVIEW

**Review by Negrescu29 — CHANGES_REQUESTED** [review]
@wwwser11 could you change the spec file name to be similar with the example Nalya gave https://redroverschool.slack.com/archives/C049HHDG0KF/p1731979320828209?thread_ts=1731956893.790899&cid=C049HHDG0KF

**Comment by LanaUno** [comment]
> @wwwser11 could you change the spec file name to be similar with the example Nalya gave https://redroverschool.slack.com/archives/C049HHDG0KF/p1731979320828209?thread_ts=1731956893.790899&cid=C049HHDG0KF

Could you please specify your request - how exactly file name should look like? Following the link didn't help.

**Comment by wwwser11** [comment]
> > @wwwser11 could you change the spec file name to be similar with the example Nalya gave https://redroverschool.slack.com/archives/C049HHDG0KF/p1731979320828209?thread_ts=1731956893.790899&cid=C049HHDG0KF
> 
> Could you please specify your request - how exactly file name should look like? Following the link didn't help.

US = US_00.001 | New Item > Create New item 
File name = newItemCreateNewItem.cy.js
describe('US_00.001 | New Item > Create New item)', ()=>{})
TC name = TC_00.001.01 | New Item > Create New item | Create item from sidebar
it('TC_00.001.01 | Create item from sidebar', ()=>{})

**Comment by LanaUno** [comment]
> > > @wwwser11 could you change the spec file name to be similar with the example Nalya gave https://redroverschool.slack.com/archives/C049HHDG0KF/p1731979320828209?thread_ts=1731956893.790899&cid=C049HHDG0KF
> > 
> > 
> > Could you please specify your request - how exactly file name should look like? Following the link didn't help.
> 
> US = US_00.001 | New Item > Create New item File name = newItemCreateNewItem.cy.js describe('US_00.001 | New Item > Create New item)', ()=>{}) TC name = TC_00.001.01 | New Item > Create New item | Create item from sidebar it('TC_00.001.01 | Create item from sidebar', ()=>{})

Ok, I see, thank you, but this file is not mine - should I change it's name? Wouldn't it better to ask those who created it?

**Review by Negrescu29 — APPROVED** [review]
LGTM

**Review by adiuzhikov — APPROVED** [review]

**Pull request merged**
