### PR TITLE
TC_00.000.18 | Create New item from the "New Item" link in the left s…

### PR DESCRIPTION
**Pull request by Olena-Novikova**
[TC_00.000.18_A ](https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/623)
New Item > Create New item |from the "New Item" link in the left sidebar.

### CODE REVIEW

**Review by LanaUno — APPROVED** [review]
Good job! Could you please add your TC link to this PR?

**Review by Irina-Didorenko — APPROVED** [review]

**Review by adiuzhikov — CHANGES_REQUESTED** [review]
Kindly adhere to the project guidelines:
1. Project Title: TC Card Name
2. Project Description: Link to Your TC Card

**Comment by Olena-Novikova** [comment]
@adiuzhikov 
Artem, is everything right now or do you need any other changes?

**Review by adiuzhikov — APPROVED** [review]
All good!

**Pull request merged**
