### PR TITLE
TC_00.000.03-A|New Item > Create New item|From the "New Item" link in the left sidebar

### PR DESCRIPTION
**Pull request by leliks818**
https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/78

### CODE REVIEW

**Comment by Negrescu29** [comment]
@leliks818 could you please update you PR with the Test Case link? it is not clear what user story your automating. thanks

**Review by Negrescu29 — CHANGES_REQUESTED** [review]
- The spec name should be the same as the user story name(check on main branch, this spec file was already created )
- describe() should have the same as the user story

**Comment by leliks818** [comment]
@Negrescu29  I don't understand the first point. 
I corrected the second point.

**Comment by Negrescu29** [comment]
> @Negrescu29 I don't understand the first point. ..."should add your test to that spec file" I corrected the second point.

https://docs.google.com/presentation/d/1cE3K9dxm0qO1eKg9JrGNpME8cdHLCgZ1/edit#slide=id.p47 check 2 point

**Review by Negrescu29 — CHANGES_REQUESTED** [review]
@leliks818 you should remove the spec files you created 
- _cypress/e2e/createItemFromsideBar.cy.js_ 
-  _cypress/e2e/createNewItemCreateJobs.cy.js_

 and add you tests here: https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/blob/499b340514bc7f8a6c175a2f20308b598757ec92/cypress/e2e/newItemCreateNewItem.cy.js  

because someone already created the spec file for this user story 
- New Item > Create New item

**Review by Rom-T — APPROVED** [review]

**Comment by Rom-T** [comment]
@Negrescu29, it is enough to leave a comment what needs to be fixed. If no configuration files were affected, we do not block PR

**Review by Negrescu29 — APPROVED** [review]
👍🏼

**Pull request merged**
