### PR TITLE
TC_01.002-01 | FreestyleProject > Rename Project > User receives an Error when the new name is invalid

### PR DESCRIPTION
**Pull request by obannikova**
TC link: https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/93

US link: https://github.com/RedRoverSchool/JenkinsQA_JS_2024_fall/issues/21

### CODE REVIEW

**Review by Negrescu29 — COMMENTED** [review]
spec file(freestyleProjectRename) doesn't match the user story name (FreestyleProject > Rename Project)

Screenshot 2024-11-19 at 15 28 31

**Comment by adiuzhikov** [comment]
You have combined at least five test cases into a lengthy one, which is unnecessary. Your test case name is _User receives an Error when the new **name is invalid**_, so you should only test this feature. I suggest you rewrite your TC card, creating new Steps. Do not forget to adhere to the TC format: Preconditions, Steps, Expected Result. Then, rewrite the test.

**Comment by obannikova** [comment]
@adiuzhikov, thank you for your feedback. My test focuses specifically on one acceptance criterion: "User receives an error when the new name is invalid." Since there are many potential error messages, the test is quite extensive. In my opinion, it shouldn't be divided into separate tests. During our last lecture, we discussed avoiding the creation of preconditions. All other test case elements are thoroughly described in the ticket.

**Comment by obannikova** [comment]
@Negrescu29 I've changed the file name. Could you please approve it if it looks good for you?

**Review by Negrescu29 — APPROVED** [review]

**Pull request merged**
